services:
    ansible:
        build: .
        container_name: ansible
        image: ansible:v1.0
        volumes:
            - ./ANSIBLE:/etc/ansible
            - ~/.ssh:/home/ansible/.ssh
        working_dir: /etc/ansible
        user: "1000:1000"
        entrypoint: ["/bin/sh", "-c", "while true; do sleep 1; done"]
        #network_mode: host