raspi:
  hosts:
    coruscant01:
      ansible_host: 192.168.1.47
    S089800DCK001:
      ansible_host: 192.168.1.13
      ansible_user: chweadm
     

oci:
  hosts:
    wireguard:
      ansible_host: 141.148.245.57
      ansible_user: ubuntu

prod:
  children:
    raspi:

local:
  hosts:
    ansible_node:
      ansible_host: 192.168.1.47
      ansible_port: 2222
      ansible_user: chweadm

