---
admin_packages_install_zsh: true
admin_packages_configure_ssh_keys: true

admin_packages_ssh_keys:
  - ~/.ssh/id_ed25519_gh_hll
  - ~/.ssh/ansible_ed25519.pub

admin_packages_zsh_plugins:
  - aliases
  - ansible
  - command-not-found
  - docker
  - docker-compose
  - git
  - git-auto-fetch
  - git-commit
  - python
  - sudo
  - tmux
  - uv
  - zsh-autosuggestions
  - zsh-syntax-highlighting

admin_packages_install_essential: true
admin_packages_install_development: true
admin_packages_install_monitoring: true
admin_packages_install_network: false
admin_packages_install_archive: false
admin_packages_install_sync: false

admin_packages_essential:
  - vim
  - tmux
  - git
  - openssh-client

admin_packages_development:
  - curl
  - wget
  - tree

admin_packages_monitoring:
  - htop
  - ncdu
  - lsof
  - strace

admin_packages_network:
  - net-tools
  - nmap
  - tcpdump

admin_packages_archive:
  - unzip
  - zip
  - tar
  - gzip

admin_packages_sync:
  - rsync
  - rclone
