---
admin_packages_install_essential: true
admin_packages_install_development: true
admin_packages_install_monitoring: true
admin_packages_install_network: false
admin_packages_install_archive: false
admin_packages_install_sync: false

admin_packages_essential:
  - vim
  - zsh
  - tmux
  - git

admin_packages_development:
  - curl
  - wget
  - tree

admin_packages_monitoring:
  - htop
  - ncdu
  - lsof
  - strace

admin_packages_network:
  - net-tools
  - nmap
  - tcpdump

admin_packages_archive:
  - unzip
  - zip
  - tar
  - gzip

admin_packages_sync:
  - rsync
  - rclone
