---
# DNS Stack role - Internal variables

# Ports to check before deployment (tag: check_ports)
dns_stack_ports_to_check:
  - "{{ dns_stack_pihole_dns_port }}"
  - "{{ dns_stack_pihole_web_port }}"
  - "{{ dns_stack_unbound_dns_port }}"
  - "{{ dns_stack_technitium_dns_port }}"
  - "{{ dns_stack_technitium_web_port }}"
